::app info
set store-view-app-name=TeleMsg
set store-view-app-version=1.0
set store-view-app-size=小于1Mb
set store-view-app-pn=com.zos.telemsgs
set store-view-app-provider=ZOS
set store-view-app-devlopment=ZOS
set store-view-app-exercise=---
set store-view-app-updatalog=第一代已发布
set store-view-app-preview=通信工具
set store-view-app-supportv=4
